apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ci-agent-data
  namespace: ci-agent
  labels:
    app.kubernetes.io/part-of: ci-agent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
